Internal Server Error: /back-in/blog/postmodel/add/
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\backends\base\base.py", line 289, in ensure_connection
    self.connect()
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\backends\base\base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\backends\postgresql\base.py", line 269, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "containers-us-west-136.railway.app" to address: Unknown host


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\admin\sites.py", line 230, in inner
    if not self.has_permission(request):
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\admin\sites.py", line 203, in has_permission
    return request.user.is_active and request.user.is_staff
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\auth\__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\auth\__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\models\sql\compiler.py", line 1558, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\backends\base\base.py", line 330, in cursor
    return self._cursor()
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\backends\base\base.py", line 306, in _cursor
    self.ensure_connection()
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\backends\base\base.py", line 288, in ensure_connection
    with self.wrap_database_errors:
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\backends\base\base.py", line 289, in ensure_connection
    self.connect()
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\backends\base\base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\django\db\backends\postgresql\base.py", line 269, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "C:\Users\User\Desktop\Projects\GLISSUS\home_venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "containers-us-west-136.railway.app" to address: Unknown host

