Internal Server Error: /back-in/blog/postmodel/add/
Traceback (most recent call last):
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(100)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\contrib\admin\options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\contrib\admin\options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\contrib\admin\options.py", line 1227, in save_model
    obj.save()
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\Blog_DuLoft\blog\models.py", line 27, in save
    super(PostModel, self).save(*args, **kwargs)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\models\sql\compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\GREAT SPEED\Desktop\PROJECTS\GLISSUS\duloft_env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(100)

